<?xml version="1.0" ?>
<sld:StyledLayerDescriptor version="1.0.0" xmlns="http://www.opengis.net/sld" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:sld="http://www.opengis.net/sld">
    <sld:UserLayer>
        <sld:LayerFeatureConstraints>
            <sld:FeatureTypeConstraint/>
        </sld:LayerFeatureConstraints>
        <sld:UserStyle>
            <sld:Name>dtm_dev-magnitude_merit.dem_m_250m_s0..0cm_2018_v1.0.tif</sld:Name>
            <sld:Description>Generated by SLD4raster - https://cbsuygulama.wordpress.com/sld4raster</sld:Description>
            <sld:Title/>
            <sld:FeatureTypeStyle>
                <sld:Name/>
                <sld:Rule>
                    <sld:RasterSymbolizer>
                        <sld:Geometry>
                            <ogc:PropertyName>grid</ogc:PropertyName>
                        </sld:Geometry>
                        <sld:Opacity>1</sld:Opacity>
                        <sld:ColorMap>
                            <sld:ColorMapEntry color="#2b83ba" label="1" opacity="1.0" quantity="1"/>
                            <sld:ColorMapEntry color="#80bfac" label="200.8" opacity="1.0" quantity="200.8"/>
                            <sld:ColorMapEntry color="#b7e2a8" label="400.6" opacity="1.0" quantity="400.6"/>
                            <sld:ColorMapEntry color="#cfecb0" label="600.4" opacity="1.0" quantity="600.4"/>
                            <sld:ColorMapEntry color="#e7f6b8" label="800.2" opacity="1.0" quantity="800.2"/>
                            <sld:ColorMapEntry color="#ffffbf" label="1000" opacity="1.0" quantity="1000"/>
                            <sld:ColorMapEntry color="#ffe8a4" label="1200" opacity="1.0" quantity="1199.8"/>
                            <sld:ColorMapEntry color="#fed189" label="1400" opacity="1.0" quantity="1399.6"/>
                            <sld:ColorMapEntry color="#feba6e" label="1599" opacity="1.0" quantity="1599.4"/>
                            <sld:ColorMapEntry color="#f17c4a" label="1799" opacity="1.0" quantity="1799.2"/>
                            <sld:ColorMapEntry color="#d7191c" label="1999" opacity="1.0" quantity="1999"/>
                        </sld:ColorMap>
                    </sld:RasterSymbolizer>
                </sld:Rule>
            </sld:FeatureTypeStyle>
        </sld:UserStyle>
    </sld:UserLayer>
</sld:StyledLayerDescriptor>
